#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <template_icons.h>

#include "lib/demo/demo.h"

int32_t template_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");

    uint8_t hash[20];
    calc_sha1("Hello world!", hash);

    printf("Hash: ");
    for(uint8_t i=0; i<20; ++i) {
        printf("%02X", hash[i]);
    }
    printf("\n");

    FURI_LOG_I("TEST", "Done");

    return 0;
}
